export const Cities = [
    { name: 'کرمان', title: 'Kermān' },
    { name: 'تهران', title: 'tehran' },
    { name: 'تبریز', title: 'tabriz' },
    { name: 'اصفهان', title: 'isfahan' },
    { name: 'یزد', title: 'yazd' },
    { name: 'شیراز', title: 'shiraz' },
    { name: 'مشهد', title: 'mashhad' },
    { name: 'قم', title: 'qom' },
    { name: 'پاریس', title: 'paris' },
    { name: 'نیویورک', title: 'new%20york' },
    { name: 'دهلی قدیم', title: 'dehli' },
    { name: 'تورنتو', title: 'toronto' },
    { name: 'برلین', title: 'berlin' },
    { name: 'توکیو', title: 'Tokyo' },
]